/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package agent.gui;

import agent.InterfaceAgent;
import agent.model.LOList;
import agent.model.LOM;
import agent.model.SearchLO;
import agent.model.Student;
import agent.model.StudentAcceptLOList;
import agent.model.StudentList;
import agent.utils.Utils;
import com.google.gson.Gson;
import jade.core.AID;
import jade.lang.acl.ACLMessage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author magir
 */
public class GUI extends javax.swing.JFrame {
    
    private InterfaceAgent interfaceAgent;
    private StudentList studentList;
    private File file;
    private LOList loList;
    private Integer sendedLOId;
    
    DefaultMutableTreeNode loTreeList;
    
    DefaultTreeModel model;
    
    /**
     * Creates new form GUI
     */
    public GUI(InterfaceAgent interfaceAgent) {
        initComponents();
        
        this.interfaceAgent = interfaceAgent;
        
        sendedLOId = 0;
        
        this.loTreeList = new DefaultMutableTreeNode("OA");
        this.model = new DefaultTreeModel(loTreeList);
        this.jtLOEvaluated.setModel(model);
    }
    
    public void fillLOList(LOList loList){
        
        this.loList = loList;
        
        jlNumLOResult.setText(String.valueOf(loList.getLOList().size()));
        
        for(LOM lom : loList.getLOList()){
            jcbLOList.addItem(lom.getTitle());
        }
        
    }
    
    public void fillTreeLO(StudentAcceptLOList studentAcceptLOList){
        

        DefaultMutableTreeNode lo = new DefaultMutableTreeNode(
                studentAcceptLOList.getLo().getTitle());
        
        for(Student student : studentAcceptLOList.getStudentList()){
            DefaultMutableTreeNode studentTreeElement = new DefaultMutableTreeNode(
                    student.getId() + ", " + student.getVARKStyle() + ", " +
                            student.getDichotomyStyle());
            
            lo.add(studentTreeElement);
        }
        
        loTreeList.add(lo);
        
        model.reload();
    }
    
    private Student getRowData(String row){
        String[] dataList = row.split(";");
        
        Student student = new Student();
        
        student.setId(dataList[0].trim());
        student.setVARKStyle(dataList[1].trim());
        student.setDichotomyStyle(dataList[2].trim());
        
        return student;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jbUploadStudentList = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jlFileName = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlNumberStudents = new javax.swing.JLabel();
        jbSimulateStudents = new javax.swing.JButton();
        jpSearchLO = new javax.swing.JPanel();
        jtfSearchString = new javax.swing.JTextField();
        jl3 = new javax.swing.JLabel();
        jbSearchLO = new javax.swing.JButton();
        jl4 = new javax.swing.JLabel();
        jlNumLOResult = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jcbLOList = new javax.swing.JComboBox<>();
        jbSendLO = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtLOEvaluated = new javax.swing.JTree();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));

        jbUploadStudentList.setText("Cargar Lista Estudiantes");
        jbUploadStudentList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUploadStudentListActionPerformed(evt);
            }
        });

        jLabel1.setText("Archivo:");

        jLabel2.setText("N° estudiantes");

        jbSimulateStudents.setText("Simular Estudiantes");
        jbSimulateStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSimulateStudentsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSimulateStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbUploadStudentList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlFileName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jlNumberStudents, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbUploadStudentList)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlFileName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jlNumberStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbSimulateStudents)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpSearchLO.setBackground(new java.awt.Color(0, 153, 153));
        jpSearchLO.setBorder(new javax.swing.border.MatteBorder(null));

        jtfSearchString.setToolTipText("Cadena de búsqueda");

        jl3.setText("Cadena de búsqueda:");

        jbSearchLO.setText("Buscar OA");
        jbSearchLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSearchLOActionPerformed(evt);
            }
        });

        jl4.setText("Resultados:");

        javax.swing.GroupLayout jpSearchLOLayout = new javax.swing.GroupLayout(jpSearchLO);
        jpSearchLO.setLayout(jpSearchLOLayout);
        jpSearchLOLayout.setHorizontalGroup(
            jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbSearchLO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jpSearchLOLayout.createSequentialGroup()
                        .addComponent(jl3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfSearchString))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSearchLOLayout.createSequentialGroup()
                        .addComponent(jl4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jlNumLOResult, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jpSearchLOLayout.setVerticalGroup(
            jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpSearchLOLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfSearchString, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl3))
                .addGap(18, 18, 18)
                .addComponent(jbSearchLO)
                .addGap(18, 18, 18)
                .addGroup(jpSearchLOLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl4)
                    .addComponent(jlNumLOResult, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        jbSendLO.setText("Agregar Objeto");
        jbSendLO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSendLOActionPerformed(evt);
            }
        });

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jtLOEvaluated.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jtLOEvaluated);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbLOList, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSendLO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jcbLOList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbSendLO)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpSearchLO, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpSearchLO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbUploadStudentListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUploadStudentListActionPerformed
        FileReader fileReader = null;
        try {
            // TODO add your handling code here:
            JFileChooser fcSeleccionarArchivo = new JFileChooser("C:\\Users\\magir\\Desktop\\Archivos\\LSSimulationMAS");
            FileNameExtensionFilter filtroExtension = new FileNameExtensionFilter("Filtrar archivos planos", "txt", "csv");
            fcSeleccionarArchivo.setFileFilter(filtroExtension);
            fcSeleccionarArchivo.showOpenDialog(this);
            file = fcSeleccionarArchivo.getSelectedFile();
            
            Integer numRows = 0;
            
            fileReader = new FileReader(file);
            BufferedReader bufferedReader = new BufferedReader(fileReader);
            
            studentList = new StudentList();
            
            String row;
            while ((row = bufferedReader.readLine()) != null) {
                numRows += 1;
                studentList.addStudent(getRowData(row));
            }
            
            System.out.println("Lista de estudiantes cargados");
            System.out.println(studentList);
            
            jlFileName.setText(file.getName());
            if(numRows > 0){
                jlNumberStudents.setText(String.valueOf(numRows));
                jpSearchLO.setVisible(true);
            }else{
                jlNumberStudents.setText("Debe cargar un archivo con datos");
                jpSearchLO.setVisible(false);
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                fileReader.close();
            } catch (IOException ex) {
                Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jbUploadStudentListActionPerformed

    private void jbSearchLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSearchLOActionPerformed
        jcbLOList.removeAllItems();
        
        Gson gson = new Gson();

        SearchLO searchLO = new SearchLO();

        searchLO.setSearchString(jtfSearchString.getText());

        String json = gson.toJson(searchLO);

        Utils utils = new Utils();
        utils.sendMessage(interfaceAgent,
            new AID("ControllerAgent", AID.ISLOCALNAME),
            "obj;" + json + ";" + "msg;" + "search lo",
            ACLMessage.INFORM);
    }//GEN-LAST:event_jbSearchLOActionPerformed

    private void jbSimulateStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSimulateStudentsActionPerformed
        Gson gson = new Gson();
        String json = gson.toJson(studentList);
        
        Utils utils = new Utils();
        utils.sendMessage(interfaceAgent, 
                new AID("ControllerAgent", AID.ISLOCALNAME), 
                "obj;" + json + ";" + "msg;" + "create simulation agents", 
                ACLMessage.INFORM);
    }//GEN-LAST:event_jbSimulateStudentsActionPerformed

    private void jbSendLOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSendLOActionPerformed
        
        LOM lom = loList.getLOList().get(jcbLOList.getSelectedIndex());
        lom.setSendedLOId(sendedLOId);
        
        sendedLOId ++;
        
        Gson gson = new Gson();
        String json = gson.toJson(lom);
        
        Utils utils = new Utils();
        utils.sendMessage(interfaceAgent, 
                new AID("ControllerAgent", AID.ISLOCALNAME), 
                "obj;" + json + ";" + "msg;" + "selected lo", 
                ACLMessage.INFORM);
    }//GEN-LAST:event_jbSendLOActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton jbSearchLO;
    private javax.swing.JButton jbSendLO;
    private javax.swing.JButton jbSimulateStudents;
    private javax.swing.JButton jbUploadStudentList;
    private javax.swing.JComboBox<String> jcbLOList;
    private javax.swing.JLabel jl3;
    private javax.swing.JLabel jl4;
    private javax.swing.JLabel jlFileName;
    private javax.swing.JLabel jlNumLOResult;
    private javax.swing.JLabel jlNumberStudents;
    private javax.swing.JPanel jpSearchLO;
    private javax.swing.JTree jtLOEvaluated;
    private javax.swing.JTextField jtfSearchString;
    // End of variables declaration//GEN-END:variables
}
